#开发环境数据库信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    # 执行的脚本位置
    locations:
      classpath: /db/migration/



  mail:
    host: smtp.qq.com  # 配置 smtp 服务器地址
    port: 25   #smtp 服务器的端口
    username: luoyong0603@foxmail.com  #配置邮箱用户名;你自己的邮箱
    password: xcpvcvequoanbega  #配置申请到的授权码;这里填写刚才短信申请到的授权码
    default-encoding: UTF-8   #配置邮件编码
    protocol: smtp #协议

# 日志设置
logging:
  level:
    # 持久层日志级别
    com.example.demo.dao: debug

